swagger: '2.0'
info:
  title: GOOGLE DRIVE API
  description: 1.1.1
  version: v1
host: 127.0.0.1:8080
schemes:
- http
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /create-document/:
    post:
      operationId: create-document_create
      description: Представление для создания Google Docs документа
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateGoogleDocViewCreate'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CreateGoogleDocViewCreate'
      tags:
      - create-document
    parameters: []
definitions:
  CreateGoogleDocViewCreate:
    required:
    - name
    - data
    type: object
    properties:
      name:
        title: Name
        type: string
        maxLength: 255
        minLength: 1
      data:
        title: Data
        type: string
        minLength: 1
